### ISSUE TITLE
issue with creating secrets

### ISSUE THREAD

**Issue by srukle** [srukle/rhodes#1]
```
$ ./rhodes.py 
Traceback (most recent call last):
  File "./rhodes.py", line 77, in <module>
    database='rhodes'
  File "/usr/local/lib/python3.6/site-packages/mysql/connector/__init__.py", line 179, in connect
    return MySQLConnection(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/mysql/connector/connection.py", line 95, in __init__
    self.connect(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/mysql/connector/abstracts.py", line 716, in connect
    self._open_connection()
  File "/usr/local/lib/python3.6/site-packages/mysql/connector/connection.py", line 210, in _open_connection
    self._ssl)
  File "/usr/local/lib/python3.6/site-packages/mysql/connector/connection.py", line 144, in _do_auth
    self._auth_switch_request(username, password)
  File "/usr/local/lib/python3.6/site-packages/mysql/connector/connection.py", line 177, in _auth_switch_request
    raise errors.get_exception(packet)
mysql.connector.errors.ProgrammingError: 1045 (28000): Access denied for user 'CRITICAL ERROR.'@'localhost' (using password: YES)
```

**Comment by srukle** [comment]
Oh, so read_secrets does not actually create secrets when it's missing.

**Comment by srukle** [comment]
Commit 74526e50a2032bfb553322c33faf26f75b198f1a resolves issue.
